# Generated by Django 5.1.7 on 2025-03-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=8080)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('restricted', 'Restricted Area'), ('normal', 'Normal Area'), ('entry_exit', 'Entry/Exit Point')], default='normal', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_employees', models.ManyToManyField(blank=True, related_name='authorized_zones', to='employees.employee')),
                ('cameras', models.ManyToManyField(related_name='zones', to='monitoring.camera')),
            ],
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='motion_snapshots/')),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='motion_clips/')),
                ('confidence', models.FloatField(default=0.0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='monitoring.camera')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField(default=0.0)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='detected_faces/')),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='employees.employee')),
                ('motion_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_detections', to='monitoring.motionevent')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('activity_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('presence', 'Presence'), ('violation', 'Violation')], max_length=20)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='zone_activities/')),
                ('is_authorized', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_activities', to='monitoring.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_activities', to='employees.employee')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='monitoring.monitoringzone')),
            ],
        ),
    ]
