# Generated by Django 5.1.7 on 2025-03-23 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringzone',
            name='authorized_employees',
        ),
        migrations.RemoveField(
            model_name='monitoringzone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monitoringzone',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='monitoringzone',
            name='zone_type',
        ),
        migrations.RemoveField(
            model_name='motionevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='motionevent',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='motionevent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='motionevent',
            name='video_clip',
        ),
        migrations.RemoveField(
            model_name='persondetection',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='persondetection',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='zoneactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='zoneactivity',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='zoneactivity',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='zoneactivity',
            name='notes',
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoringzone',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoringzone',
            name='coordinates',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='persondetection',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='person_detections/'),
        ),
        migrations.AddField(
            model_name='zoneactivity',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='monitoringzone',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='motion_events/'),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persondetection',
            name='bounding_box',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='persondetection',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zoneactivity',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera'),
        ),
        migrations.AlterField(
            model_name='zoneactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
